server:
  port: ${port:8000}
  
spring:
  application:
    name: api-gateway-service
  cloud:
    config:
      uri: ${CONFIG_SERVER:http://localhost:8011}

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8012/eureka/}
    healthcheck:
      enabled: true